"""add_project_type

Revision ID: 0fb623d18f06
Revises: 1ebcd87346bf
Create Date: 2026-04-02 21:36:18.909754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb623d18f06'
down_revision: Union[str, None] = '1ebcd87346bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.String(length=32), server_default='tabular', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
