"""add_imaging_tables

Revision ID: 1ebcd87346bf
Revises: b3c4d5e6f7a8
Create Date: 2026-04-02 16:59:28.476573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebcd87346bf'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imaging_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_model', sa.String(length=128), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imaging_sessions_id'), 'imaging_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_imaging_sessions_project_id'), 'imaging_sessions', ['project_id'], unique=False)
    op.create_table('imaging_trained_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('artifacts_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['imaging_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imaging_trained_models_id'), 'imaging_trained_models', ['id'], unique=False)
    op.create_index(op.f('ix_imaging_trained_models_project_id'), 'imaging_trained_models', ['project_id'], unique=False)
    op.create_index(op.f('ix_imaging_trained_models_session_id'), 'imaging_trained_models', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imaging_trained_models_session_id'), table_name='imaging_trained_models')
    op.drop_index(op.f('ix_imaging_trained_models_project_id'), table_name='imaging_trained_models')
    op.drop_index(op.f('ix_imaging_trained_models_id'), table_name='imaging_trained_models')
    op.drop_table('imaging_trained_models')
    op.drop_index(op.f('ix_imaging_sessions_project_id'), table_name='imaging_sessions')
    op.drop_index(op.f('ix_imaging_sessions_id'), table_name='imaging_sessions')
    op.drop_table('imaging_sessions')
    # ### end Alembic commands ###
