"""add target_column to projects

Revision ID: 59d7439e2a53
Revises: b8f3619f3ae2
Create Date: 2026-01-24 01:10:34.998520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d7439e2a53'
down_revision: Union[str, None] = 'b8f3619f3ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('target_column', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'target_column')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    # ### end Alembic commands ###
