"""add processing_operations

Revision ID: a96b219a7482
Revises: 616da11c002c
Create Date: 2026-01-26 12:06:25.921175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a96b219a7482"
down_revision: Union[str, None] = "616da11c002c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("op_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "columns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_operations_dataset_id"), "processing_operations", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_processing_operations_id"), "processing_operations", ["id"], unique=False)
    op.create_index(op.f("ix_processing_operations_project_id"), "processing_operations", ["project_id"], unique=False)
    op.create_index(op.f("ix_processing_operations_user_id"), "processing_operations", ["user_id"], unique=False)
    op.create_index("ix_processing_ops_proj_ds", "processing_operations", ["project_id", "dataset_id"], unique=False)

    # add params safely (works even if table had existing rows in some envs)
    op.add_column(
        "processing_operations",
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.execute("UPDATE processing_operations SET params='{}'::jsonb WHERE params IS NULL")
    op.alter_column("processing_operations", "params", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_processing_ops_proj_ds", table_name="processing_operations")
    op.drop_index(op.f("ix_processing_operations_user_id"), table_name="processing_operations")
    op.drop_index(op.f("ix_processing_operations_project_id"), table_name="processing_operations")
    op.drop_index(op.f("ix_processing_operations_id"), table_name="processing_operations")
    op.drop_index(op.f("ix_processing_operations_dataset_id"), table_name="processing_operations")

    # ✅ IMPORTANT: drop_table suffit (NE PAS drop_column après)
    op.drop_table("processing_operations")
    # ### end Alembic commands ###
