"""add timestamps to projects

Revision ID: b89bb09fa136
Revises: c48386e2ee65
Create Date: 2026-01-22 12:20:59.388919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b89bb09fa136'
down_revision: Union[str, None] = 'c48386e2ee65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ix_projects_id', table_name='projects')
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
