"""ReportService — orchestrates context build → LLM router → SSE streaming.

Streaming protocol (SSE, per plan §6):

    event: chunk
    data: {"section": "summary", "text": "..."}

    event: chunk
    data: {"section": "key_factors", "items": [...]}

    event: done
    data: {"report_id": "...", "provider": "groq", "latency_ms": 1200}

The ``disclaimer`` is rewritten server-side after generation, never trusted
to the LLM.
"""
from __future__ import annotations

import json
import logging
import time
import uuid
from typing import AsyncGenerator

from app.services.reporting.context_builder import ReportContext, localize_direction
from app.services.reporting.llm_client import LLMClient, LLMReport, TemplateClient
from app.services.reporting.llm_client.router import LLMRouter
from app.services.reporting.observability import event_from_meta, log_event
from app.services.reporting.validator import ReportValidator

logger = logging.getLogger(__name__)


# Bump whenever the post-processed report shape changes (new fields, new
# section semantics, new task-type handling). The cache layer only accepts
# entries whose stored ``schema_version`` matches this constant — older
# reports fall through to regeneration. Bumping is safer than purging the
# whole table because in-flight regeneration replaces stale rows in place.
REPORT_SCHEMA_VERSION = 2


_DISCLAIMER_TEXT = {
    "fr": (
        "Ce rapport est généré automatiquement par un modèle d'apprentissage "
        "automatique. Il ne constitue pas un avis médical et ne remplace pas "
        "l'évaluation d'un professionnel de santé qualifié. Toute décision "
        "clinique doit être prise par un médecin."
    ),
    "en": (
        "This report is automatically generated by a machine learning model. "
        "It does not constitute medical advice and does not replace evaluation "
        "by a qualified healthcare professional. Any clinical decision must be "
        "made by a physician."
    ),
}


# ── Section ordering — controls SSE chunk order ───────────────────────────────
_SECTION_ORDER: tuple[str, ...] = (
    "prediction",
    "risk_level",
    "chart_data",
    "summary",
    "key_factors",
    "context",
    "limitations",
    "next_steps",
    "what_to_change",
    "disclaimer",
)


def _sse(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"


async def stream_existing_report(
    report: LLMReport,
    meta: dict,
) -> AsyncGenerator[str, None]:
    """Emit SSE chunks for an already-built report.

    Used by the cache hit path so the frontend stream protocol is identical
    whether the report was just generated or pulled from the DB cache.
    """
    for section in _SECTION_ORDER:
        if section not in report:
            continue
        yield _sse("chunk", {"section": section, "content": report[section]})
    yield _sse("done", meta)


class ReportService:
    """Façade over the report pipeline."""

    def __init__(
        self,
        client: LLMClient | None = None,
        *,
        router: LLMRouter | None = None,
        validator: ReportValidator | None = None,
    ) -> None:
        """Build a service.

        Either ``router`` or ``client`` may be passed (router wins). The
        single-client form is mainly for focused tests; it is wrapped in an
        ``LLMRouter`` with TemplateClient appended automatically.
        """
        if router is not None:
            self._router = router
        else:
            initial = [client] if client is not None else [TemplateClient()]
            self._router = LLMRouter(initial, validator=validator)

    # ── Synchronous full-report generation ───────────────────────────────────

    def generate(self, context: ReportContext) -> tuple[LLMReport, dict]:
        """Generate, validate, post-process. Returns (report, meta).

        Delegates the failure matrix (plan §8) to the LLMRouter. Returns:
        - ``provider``: name of the client whose output won
        - ``retries``: 0 if first try passed, 1 if reinforced retry was used
        - ``fallback_reason``: last failure encountered before the winning
          provider; ``None`` if the very first attempt succeeded
        - ``attempts``: full chain trace for observability
        """
        started = time.perf_counter()
        result = self._router.generate(context)
        report = self._postprocess(result.report, context)
        meta = {
            "report_id": f"rpt_{uuid.uuid4().hex[:12]}",
            "provider": result.provider,
            "latency_ms": int((time.perf_counter() - started) * 1000),
            "lang": context.lang,
            "retries": result.retries,
            "fallback_reason": result.fallback_reason,
            "attempts": [
                {"client": a.client, "reinforced": a.reinforced, "outcome": a.outcome}
                for a in result.attempts
            ],
        }
        # Emit a structured event for ops dashboards. The dedicated logger
        # ``reporting.events`` lets deployments route this to its own sink.
        log_event(
            event_from_meta(
                prediction_id=context.prediction_id,
                lang=context.lang,
                meta=meta,
                model=context.model_name,
            )
        )
        return report, meta

    # ── Streaming variant — yields SSE-formatted strings ─────────────────────

    async def generate_stream(
        self,
        context: ReportContext,
    ) -> AsyncGenerator[str, None]:
        """Stream the report section by section as SSE events.

        Current LLM clients return a full validated dict. The service then
        splits it into stable section-level chunks.
        """
        report, meta = self.generate(context)
        async for chunk in stream_existing_report(report, meta):
            yield chunk

    # ── Post-processing ──────────────────────────────────────────────────────

    def _postprocess(self, report: LLMReport, context: ReportContext) -> LLMReport:
        """Server-side fixups that must happen regardless of backend.

        - Disclaimer is always rewritten with the canonical text. The LLM is
          told it must emit the literal string ``PLACEHOLDER`` and it gets
          replaced here. This guarantees the disclaimer can never be edited,
          weakened or omitted by the model.
        - Missing required keys fall back to safe defaults so the frontend can
          always render the panel.
        """
        out = dict(report) if isinstance(report, dict) else {}
        out["schema_version"] = REPORT_SCHEMA_VERSION
        out["disclaimer"] = _DISCLAIMER_TEXT.get(context.lang, _DISCLAIMER_TEXT["fr"])
        out["risk_level"] = _compute_risk_level(context)
        out["chart_data"] = _build_chart_data(context)

        out.setdefault(
            "prediction",
            {
                "label": context.label,
                "confidence_text": context.confidence_text,
                "score_pct": context.score_pct,
            },
        )
        out.setdefault("summary", "")
        out.setdefault("key_factors", [])
        out.setdefault("context", "")
        out.setdefault("limitations", "")
        out.setdefault("next_steps", "")
        out.setdefault("what_to_change", [])
        out["key_factors"] = self._repair_key_factors(out.get("key_factors"), context)
        out["what_to_change"] = _sanitize_what_to_change(out.get("what_to_change"), context)

        return out

    @staticmethod
    def _repair_key_factors(raw_factors: object, context: ReportContext) -> list[dict]:
        """Keep LLM prose, but make factual fields deterministic.

        The LLM may omit or blank ``value`` even when the context contains it.
        UI/PDF tables should never lose the server-derived label/value/range.
        """
        factors = raw_factors if isinstance(raw_factors, list) else []
        repaired: list[dict] = []
        context_features = context.top_features

        max_len = max(len(factors), len(context_features))
        for idx in range(max_len):
            raw = factors[idx] if idx < len(factors) and isinstance(factors[idx], dict) else {}
            feat = context_features[idx] if idx < len(context_features) else None
            item = dict(raw)

            if feat is not None:
                if _blank(item.get("label")) or str(item.get("label", "")).startswith(("num__", "cat__")):
                    item["label"] = feat.label
                if _blank(item.get("value")):
                    item["value"] = feat.value
                if item.get("normal_range") in (None, "", "—", "-"):
                    item["normal_range"] = feat.normal_range
                # Always override the LLM's direction wording with the
                # canonical semantic label. The LLM is allowed to write
                # "augmente" / "diminue" in prose, but the structured
                # ``direction`` field that drives the frontend badge must be
                # the deterministic Préoccupant / Rassurant token.
                item["direction"] = localize_direction(feat.direction, context.lang)
                item.setdefault("explanation", "")
                # Status is always overridden server-side (derived from glossary normal_range).
                item["status"] = _status_from_position(feat.position_vs_normal)

            if item:
                repaired.append(item)

        return repaired


def _blank(value: object) -> bool:
    return value is None or str(value).strip() in {"", "—", "-"}


def _build_chart_data(context: ReportContext) -> dict:
    """Chart-ready payload sent as a dedicated SSE chunk.

    The frontend renders this as inline SVG (no library). No LLM involvement —
    all values come directly from the already-validated ReportContext.

    For regression, ``score_pct`` and ``threshold_pct`` are nullified so the
    frontend gauge logic can branch on ``is_classification`` and render a
    dedicated regression layout (predicted-value badge instead of a 0–100
    bar). The factors list is shared between both task types — bar lengths
    still encode |weight| in either case.
    """
    is_classification = context.task_type == "classification"
    if is_classification:
        score_pct = (
            round(float(context.score) * 100)
            if context.score is not None
            else None
        )
        threshold_pct = (
            round(float(context.threshold_value) * 100)
            if context.threshold_value is not None
            else 50
        )
    else:
        # Regression: a percentage gauge would be misleading. The frontend
        # falls back to showing the textual prediction badge alone.
        score_pct = None
        threshold_pct = None

    return {
        "score_pct": score_pct,
        "threshold_pct": threshold_pct,
        "is_classification": is_classification,
        "factors": [
            {
                "label": feat.label,
                "value": feat.value,
                "direction": feat.direction,
                "weight": round(abs(feat.weight), 3),
                "status": _status_from_position(feat.position_vs_normal),
                "normal_range": feat.normal_range,
            }
            for feat in context.top_features
        ],
    }


def _compute_risk_level(context: ReportContext) -> str:
    """Deterministic risk-level token consumed by the frontend badge.

    Classification: 3-level scale derived from (is_positive_prediction,
    confidence) — "high" for confident positives, "low" for confident
    negatives, "medium" otherwise.

    Regression: there is no positive/negative axis, so "risk" maps to the
    *reliability* of the estimate rather than a clinical risk level. The
    frontend re-uses the same badge component but with neutral colours.
    Returns "estimate_reliable" / "estimate_moderate" / "estimate_uncertain"
    so the frontend can pick a tailored colour and label without having
    to re-derive the bucket.
    """
    if context.task_type == "regression":
        if context.confidence_text in ("élevée", "high"):
            return "estimate_reliable"
        if context.confidence_text in ("modérée", "moderate"):
            return "estimate_moderate"
        return "estimate_uncertain"

    if context.task_type != "classification":
        return "unknown"

    # Positivity is derived from the score vs the alert threshold — the SAME
    # signal that labels the result "préoccupant / rassurant" in the chart.
    # This guarantees the risk badge can never contradict the displayed score
    # (e.g. a 100 % concerning result must not show "Risque faible"). The
    # fragile label-string comparison is only a fallback when no score exists.
    if context.score is not None:
        threshold = (
            float(context.threshold_value)
            if context.threshold_value is not None
            else 0.5
        )
        is_positive = float(context.score) >= threshold
    else:
        raw = context.class_context.raw_label
        pos = context.class_context.positive_class
        is_positive = bool(
            pos
            and raw.lower().rstrip("0").rstrip(".") == pos.lower().rstrip("0").rstrip(".")
        )

    high_conf = context.confidence_text in ("élevée", "high")
    low_conf = context.confidence_text in ("faible", "low")

    if is_positive:
        return "high" if high_conf else "medium"
    else:
        return "medium" if low_conf else "low"


def _status_from_position(position: str) -> str:
    """Map FeatureContribution.position_vs_normal to a display status."""
    return {
        "above": "abnormal_high",
        "below": "abnormal_low",
        "within": "normal",
    }.get(position, "unknown")


def build_default_router() -> LLMRouter:
    """Construct the default LLM router chain from app settings.

    Configured backends are tried in order: Ollama, then Groq. TemplateClient
    is always appended by the router as the deterministic floor.
    """
    chain: list[LLMClient] = []

    # Imported lazily so test envs without external LLM config still work.
    try:
        from app.core.config import settings
        from app.services.reporting.llm_client import (
            GroqClient,
            GroqConfig,
            GroqError,
            OllamaClient,
            OllamaConfig,
        )
    except Exception as exc:  # pragma: no cover — defensive guard
        logger.warning("reporting.default_router_fallback: %s", exc)
        return LLMRouter([TemplateClient()])

    ollama_url = getattr(settings, "REPORTING_OLLAMA_URL", "").strip()
    ollama_model = getattr(settings, "REPORTING_OLLAMA_MODEL", "").strip()
    if ollama_url and ollama_model:
        chain.append(
            OllamaClient(
                OllamaConfig(
                    base_url=ollama_url,
                    model=ollama_model,
                    timeout_s=int(getattr(settings, "REPORTING_OLLAMA_TIMEOUT_S", 30)),
                )
            )
        )

    groq_key = getattr(settings, "REPORTING_GROQ_API_KEY", "").strip()
    if groq_key:
        try:
            chain.append(
                GroqClient(
                    GroqConfig(
                        api_key=groq_key,
                        model=getattr(settings, "REPORTING_GROQ_MODEL", "llama-3.3-70b-versatile"),
                    )
                )
            )
        except GroqError:
            # Empty/invalid key — skip silently.
            pass

    return LLMRouter(chain)  # TemplateClient appended internally


_AWAY_PHRASES_FR = (
    "éloignerait",
    "éloigner",
    "aggraverait",
    "aggraver",
    "augmenterait le risque",
    "rendrait le profil plus préoccupant",
    "plus préoccupant",
)
_AWAY_PHRASES_EN = (
    "move further",
    "further from",
    "would worsen",
    "increase the risk",
    "make the profile more concerning",
    "more concerning",
)


def _is_anti_recommendation(why_it_matters: str, lang: str) -> bool:
    """True when the LLM prose admits the change moves AWAY from reassurance.

    A counterfactual that worsens the prediction has no place in a
    "what to change" section; surfacing it confuses the patient and
    contradicts the very purpose of the section. The CF generator can
    produce such rows on noisy model surfaces (constant-σ pushes when
    no SHAP background is available), so we filter them server-side
    rather than rely on the LLM to suppress them.
    """
    if not why_it_matters:
        return False
    text = why_it_matters.lower()
    phrases = _AWAY_PHRASES_FR if lang == "fr" else _AWAY_PHRASES_EN
    return any(p in text for p in phrases)


def _is_negligible_change(cf: object) -> bool:
    """Drop changes whose magnitude is too small to be clinically meaningful.

    A delta below 2 % of the original value AND below 1 unit in absolute
    terms is treated as noise from the CF search rather than a real
    suggestion. This guards against the constant ±0.9 artefact seen when
    the background distribution is unavailable.
    """
    try:
        import re as _re
        match_orig = _re.search(r"-?\d+(?:\.\d+)?", str(getattr(cf, "current_value", "")))
        match_delta = _re.search(r"-?\d+(?:\.\d+)?", str(getattr(cf, "magnitude_text", "")))
        if not match_orig or not match_delta:
            return False
        orig = abs(float(match_orig.group()))
        delta = abs(float(match_delta.group()))
    except (TypeError, ValueError):
        return False
    if delta < 1.0 and (orig == 0 or delta / orig < 0.02):
        return True
    return False


def _sanitize_what_to_change(raw: object, context: ReportContext) -> list[dict]:
    """Keep only entries that are coherent and clinically meaningful.

    The LLM may invent extra rows (hallucinated targets) or drop entries it
    found awkward to phrase. We anchor on the server-built list: every CF
    suggestion gets at least the structured fields; LLM prose fills the
    free-text ones. Two filters then run:

    - **Anti-recommendation filter**: rows whose prose admits the change
      worsens the result are removed. These contradict the section's
      purpose and arise when the CF search ran without a usable background
      distribution.
    - **Negligible-delta filter**: rows whose magnitude is clinically
      trivial (< 2 % relative AND < 1 unit absolute) are removed. They
      are usually a side-effect of constant-σ pushing.

    Empty list when no CF was computed (regression, or DiCE failed to
    converge) or after filtering wipes everything.
    """
    if not context.counterfactual_changes:
        return []
    by_label = {c.label: c for c in context.counterfactual_changes}
    raw_items = raw if isinstance(raw, list) else []
    by_factor: dict[str, dict] = {}
    for item in raw_items:
        if not isinstance(item, dict):
            continue
        factor = str(item.get("factor", "")).strip()
        if factor in by_label:
            by_factor[factor] = item

    out: list[dict] = []
    for cf in context.counterfactual_changes:
        if _is_negligible_change(cf):
            continue
        llm = by_factor.get(cf.label, {})
        why = str(llm.get("why_it_matters", "")).strip()
        if _is_anti_recommendation(why, context.lang):
            continue
        out.append(
            {
                "factor": cf.label,
                "current": cf.current_value,
                "target": cf.suggested_value,
                "direction": localize_direction(cf.direction, context.lang),
                "magnitude_text": cf.magnitude_text,
                "normal_range": cf.normal_range,
                "change_text": str(llm.get("change_text", "")).strip(),
                "why_it_matters": why,
            }
        )
    return out


__all__ = ["ReportService", "build_default_router", "stream_existing_report"]
