"""ReportService — orchestrates context build → LLM router → SSE streaming.

Streaming protocol (SSE, per plan §6):

    event: chunk
    data: {"section": "summary", "text": "..."}

    event: chunk
    data: {"section": "key_factors", "items": [...]}

    event: done
    data: {"report_id": "...", "provider": "groq", "latency_ms": 1200}

The ``disclaimer`` is rewritten server-side after generation, never trusted
to the LLM.
"""
from __future__ import annotations

import json
import logging
import time
import uuid
from typing import AsyncGenerator

from app.services.reporting.context_builder import ReportContext
from app.services.reporting.llm_client import LLMClient, LLMReport, TemplateClient
from app.services.reporting.llm_client.router import LLMRouter
from app.services.reporting.observability import event_from_meta, log_event
from app.services.reporting.validator import ReportValidator

logger = logging.getLogger(__name__)


_DISCLAIMER_TEXT = {
    "fr": (
        "Ce rapport est généré automatiquement par un modèle d'apprentissage "
        "automatique. Il ne constitue pas un avis médical et ne remplace pas "
        "l'évaluation d'un professionnel de santé qualifié. Toute décision "
        "clinique doit être prise par un médecin."
    ),
    "en": (
        "This report is automatically generated by a machine learning model. "
        "It does not constitute medical advice and does not replace evaluation "
        "by a qualified healthcare professional. Any clinical decision must be "
        "made by a physician."
    ),
}


# ── Section ordering — controls SSE chunk order ───────────────────────────────
_SECTION_ORDER: tuple[str, ...] = (
    "prediction",
    "summary",
    "key_factors",
    "context",
    "limitations",
    "next_steps",
    "disclaimer",
)


def _sse(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"


async def stream_existing_report(
    report: LLMReport,
    meta: dict,
) -> AsyncGenerator[str, None]:
    """Emit SSE chunks for an already-built report.

    Used by the cache hit path so the frontend stream protocol is identical
    whether the report was just generated or pulled from the DB cache.
    """
    for section in _SECTION_ORDER:
        if section not in report:
            continue
        yield _sse("chunk", {"section": section, "content": report[section]})
    yield _sse("done", meta)


class ReportService:
    """Façade over the report pipeline."""

    def __init__(
        self,
        client: LLMClient | None = None,
        *,
        router: LLMRouter | None = None,
        validator: ReportValidator | None = None,
    ) -> None:
        """Build a service.

        Either ``router`` or ``client`` may be passed (router wins). The
        single-client form is mainly for focused tests; it is wrapped in an
        ``LLMRouter`` with TemplateClient appended automatically.
        """
        if router is not None:
            self._router = router
        else:
            initial = [client] if client is not None else [TemplateClient()]
            self._router = LLMRouter(initial, validator=validator)

    # ── Synchronous full-report generation ───────────────────────────────────

    def generate(self, context: ReportContext) -> tuple[LLMReport, dict]:
        """Generate, validate, post-process. Returns (report, meta).

        Delegates the failure matrix (plan §8) to the LLMRouter. Returns:
        - ``provider``: name of the client whose output won
        - ``retries``: 0 if first try passed, 1 if reinforced retry was used
        - ``fallback_reason``: last failure encountered before the winning
          provider; ``None`` if the very first attempt succeeded
        - ``attempts``: full chain trace for observability
        """
        started = time.perf_counter()
        result = self._router.generate(context)
        report = self._postprocess(result.report, context)
        meta = {
            "report_id": f"rpt_{uuid.uuid4().hex[:12]}",
            "provider": result.provider,
            "latency_ms": int((time.perf_counter() - started) * 1000),
            "lang": context.lang,
            "retries": result.retries,
            "fallback_reason": result.fallback_reason,
            "attempts": [
                {"client": a.client, "reinforced": a.reinforced, "outcome": a.outcome}
                for a in result.attempts
            ],
        }
        # Emit a structured event for ops dashboards. The dedicated logger
        # ``reporting.events`` lets deployments route this to its own sink.
        log_event(
            event_from_meta(
                prediction_id=context.prediction_id,
                lang=context.lang,
                meta=meta,
                model=context.model_name,
            )
        )
        return report, meta

    # ── Streaming variant — yields SSE-formatted strings ─────────────────────

    async def generate_stream(
        self,
        context: ReportContext,
    ) -> AsyncGenerator[str, None]:
        """Stream the report section by section as SSE events.

        Current LLM clients return a full validated dict. The service then
        splits it into stable section-level chunks.
        """
        report, meta = self.generate(context)
        async for chunk in stream_existing_report(report, meta):
            yield chunk

    # ── Post-processing ──────────────────────────────────────────────────────

    def _postprocess(self, report: LLMReport, context: ReportContext) -> LLMReport:
        """Server-side fixups that must happen regardless of backend.

        - Disclaimer is always rewritten with the canonical text. The LLM is
          told it must emit the literal string ``PLACEHOLDER`` and it gets
          replaced here. This guarantees the disclaimer can never be edited,
          weakened or omitted by the model.
        - Missing required keys fall back to safe defaults so the frontend can
          always render the panel.
        """
        out = dict(report) if isinstance(report, dict) else {}
        out["disclaimer"] = _DISCLAIMER_TEXT.get(context.lang, _DISCLAIMER_TEXT["fr"])

        out.setdefault(
            "prediction",
            {
                "label": context.label,
                "confidence_text": context.confidence_text,
                "score_pct": context.score_pct,
            },
        )
        out.setdefault("summary", "")
        out.setdefault("key_factors", [])
        out.setdefault("context", "")
        out.setdefault("limitations", "")
        out.setdefault("next_steps", "")
        out["key_factors"] = self._repair_key_factors(out.get("key_factors"), context)

        return out

    @staticmethod
    def _repair_key_factors(raw_factors: object, context: ReportContext) -> list[dict]:
        """Keep LLM prose, but make factual fields deterministic.

        The LLM may omit or blank ``value`` even when the context contains it.
        UI/PDF tables should never lose the server-derived label/value/range.
        """
        factors = raw_factors if isinstance(raw_factors, list) else []
        repaired: list[dict] = []
        context_features = context.top_features

        max_len = max(len(factors), len(context_features))
        for idx in range(max_len):
            raw = factors[idx] if idx < len(factors) and isinstance(factors[idx], dict) else {}
            feat = context_features[idx] if idx < len(context_features) else None
            item = dict(raw)

            if feat is not None:
                if _blank(item.get("label")) or str(item.get("label", "")).startswith(("num__", "cat__")):
                    item["label"] = feat.label
                if _blank(item.get("value")):
                    item["value"] = feat.value
                if item.get("normal_range") in (None, "", "—", "-"):
                    item["normal_range"] = feat.normal_range
                item.setdefault("direction", feat.direction)
                item.setdefault("explanation", "")

            if item:
                repaired.append(item)

        return repaired


def _blank(value: object) -> bool:
    return value is None or str(value).strip() in {"", "—", "-"}


def build_default_router() -> LLMRouter:
    """Construct the default LLM router chain from app settings.

    Configured backends are tried in order: Ollama, then Groq. TemplateClient
    is always appended by the router as the deterministic floor.
    """
    chain: list[LLMClient] = []

    # Imported lazily so test envs without external LLM config still work.
    try:
        from app.core.config import settings
        from app.services.reporting.llm_client import (
            GroqClient,
            GroqConfig,
            GroqError,
            OllamaClient,
            OllamaConfig,
        )
    except Exception as exc:  # pragma: no cover — defensive guard
        logger.warning("reporting.default_router_fallback: %s", exc)
        return LLMRouter([TemplateClient()])

    ollama_url = getattr(settings, "REPORTING_OLLAMA_URL", "").strip()
    ollama_model = getattr(settings, "REPORTING_OLLAMA_MODEL", "").strip()
    if ollama_url and ollama_model:
        chain.append(
            OllamaClient(
                OllamaConfig(
                    base_url=ollama_url,
                    model=ollama_model,
                    timeout_s=int(getattr(settings, "REPORTING_OLLAMA_TIMEOUT_S", 30)),
                )
            )
        )

    groq_key = getattr(settings, "REPORTING_GROQ_API_KEY", "").strip()
    if groq_key:
        try:
            chain.append(
                GroqClient(
                    GroqConfig(
                        api_key=groq_key,
                        model=getattr(settings, "REPORTING_GROQ_MODEL", "llama-3.3-70b-versatile"),
                    )
                )
            )
        except GroqError:
            # Empty/invalid key — skip silently.
            pass

    return LLMRouter(chain)  # TemplateClient appended internally


__all__ = ["ReportService", "build_default_router", "stream_existing_report"]
